### ISSUE TITLE
koe mano 

### ISSUE THREAD

**Issue by wwendell1** [guto-alves/naruto-game#4]
koe mano como eu faço pra rodar em local e colocar o apk pros demais amigos jogar to iniciando ainda xD

**Comment by guto-alves** [comment]
Tente seguir as instruções no [README.md](https://github.com/guto-alves/naruto-game#running-locally) de como rodar localmente. Qualquer problema me avise por favor!

**Comment by guto-alves** [comment]
Desculpe a demora, fiz algumas correções e atualizei o projeto.

**Comment by wwendell1** [comment]
e sobre aquele projeto do naruto game (versão web) que estar em php, aquele
que te mandei por mensagem no wpp, será que conseguimos colocar ele online
?

Em qui., 25 de jan. de 2024 às 21:12, Gustavo Alves <
***@***.***> escreveu:
